version: "0.5"
log_location: ./var/log/processes.log

processes:
  symfony:
    command: "rr serve -p -c .rr.dev.yaml --debug"
    restart: true
  symfony-message-consumer:
    command: "symfony run --watch=config,src,vendor bin/console messenger:consume async --limit=10 --time-limit=300 --no-interaction -vv"
    restart: true

