name: Tests

on:
  push:
  merge_group:
jobs:
  # TODO: build container once, before running static-analysis
  static-analysis:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: nix-shell --pure --run "bash -euxo pipefail {0}"
    strategy: 
        fail-fast: false
        matrix:
            check:
              - vendor/bin/psalm --output-format=github
              - vendor/bin/ecs
              - bin/console lint:twig templates --no-interaction --format=github
              - bin/console lint:yaml . *.yaml --parse-tags --no-interaction --format=github
              - bin/console lint:container --no-interaction
              - bin/console lint:xliff translations --no-interaction --format=github
              - composer validate composer.json --no-check-publish
              - symfony security:check
              # TODO: add more ci-checks
              #      vendor/bin/parallel-lint src public migrations config
              #      XDEBUG_MODE=off bin/composer-require-checker --no-interaction --config-file=$PWD/composer-require-checker.json
              #      vendor/bin/config-transformer --dry-run
              #      bin/console debug:translation --all --only-missing en
              #      vendor/bin/rector --dry-run
              #      vendor/bin/phpstan -v --memory-limit=1G {{ if output == "github" { "--error-format=github" } else { "" } }}
              #      cd .. && pnpm spectral lint openapi.yaml {{ if output == "github" { "--format=github-actions" } else { "" } }
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        # TODO: cache composer dependencies
        # TODO: check why --ignore-platform-req=ext-redis is needed
      - run: composer install --ignore-platform-req=ext-redis
      - run: bin/console cache:warmup
      - run: ${{ matrix.check }}
        
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      # TODO: cache the build
      - shell: nix-shell --pure --run "bash -euxo pipefail {0}"
        run: |
            # TODO: cache composer dependencies
            # TODO: check why --ignore-platform-req=ext-redis is needed
            composer install --ignore-platform-req=ext-redis
            XDEBUG_MODE=coverage vendor/bin/phpunit --order-by=random --stop-on-error --stop-on-failure
